pipeline:
  docker:
    image: plugins/docker
    repo: quay.io/uswitch/terrafying
    registry: quay.io
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_COMMIT_SHA}
      - ${DRONE_COMMIT_BRANCH}
    when:
      event: push

  docker-latest:
    image: plugins/docker
    repo: quay.io/uswitch/terrafying
    registry: quay.io
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_COMMIT_SHA}
      - latest
    when:
      event: push
      branch: master
